const songLyrics = {
  '1.mp3': `Matalbi ho ja zara matlabi /  Duniya ki sunta hai kyun / Khud ki bhi sun le kabhi /////// Matalbi ho ja zara matlabi / Duniya ki sunta hai kyun / Khud ki bhi sun le kabhi /////// Kuch baat ghalat bhi ho jaaye / Kuch der ye dil bhi kho jaaye / Befikar dhadkane, iss tarah se chale / Shor goonje yahaan se wahaan /////// Sooraj dooba hai yaaron / Do ghoont nashe ke maaro / Raste bhula do saare gharbaar ke / Sooraj dooba hain yaaron / Do ghoont nashe ke maaro / Gham tum bhula do saare sansaar ke /////// Ask me for anything / I can give you everything / Raste bhula do saare gharbaar ke / Ask me for anything / I can give you everything / Gham tum bhula do saare sansaar ke / (ooo...) /////// Ataa pataa rahe na kisi ka humein / Yehi kahe ye pal zindagi ka humein / Ataa pataa rahe na kisi ka / Yehi kahe ye pal zindagi ka / Ki khudgarz si khwahish liye / Be-saans bhi hum-tum jiye / Hai gulaabi gulaabi samaa.. /////// Suraj dooba hai yaaron / Do ghoont nashe ke maaro / Raste bhula do saare gharbaar ke / Suraj dooba hai yaaron / Do ghoont nashe ke maaro / Gham tum bhula do saare sansaar ke /////// Matalbi ho ja zara matlabi / Duniya ki sunta hai kyun.. / Khud ki bhi sun le kabhi /////// Chale nahi ude aasmaan pe abhi.. / Pata na ho hai jaana kahaan pe abhi.. / Chale nahi ude aasmaan pe / Pata na ho hai jaana kahaan pe / Ki be-manzilein ho sab raaste / Duniya se hon zara faasle / Kuch khud se bhi ho dooriyaa /////// Sooraj dooba hai yaaron / Do ghoont nashe ke maaro / Raste bhula do saare gharbaar ke / Sooraj dooba hain yaaron / Do ghoont nashe ke maar / Gham tum bhula do saare sansaar ke ////// Ask me for anything  / I can give you everything / (ooo... ) / Ask me for anything / I can give you everything (ooo... )`,

  '2.mp3': `Kondhal Vannanai Kovalanaai / Vennai Unda Va Yennin Ullam Kavarthanae / Kondhal Vannanai Kovalanaai / Vennai Unda Va Yennin Ullam Kavarthanae / Anda Kula Ne Arandha Nin Amudinai (x2) / Kanda Kangal Mai Thonrinai Kaanathey ///////
  Ban ke titli dil udaa udaa udaa hai kaheen door / Chal ke khushboo se judaa judaa judaa hai kahin door ////// / aadse ye kaise, ansune se jaise / Choome andheron ko, koi noor.. / Ban ke titlee dil udaa udaa uda hai kahin door.. ///////
  Sirf keh jaaun yaa aasmaan pe likh doon / Teree taareefon mein chashme baddoor ////// / Ban ke titli dil udaa udaa udaa hai kaheen door / Chal ke khushboo se judaa judaa judaa hai kahin door ///////
  Kondhal Vannanai Kovalanaai / Vennai Unda Va Yennin Ullam Kavarthanae / Anda Kula Ne Arandha Nin Amudinai / Kanda Kangal Mai Thonrinai Kaanathey ///////
  Bhoori Bhoori, Aankhein Teri, Kanakhiyon Se Tez Teer Kitne Chhode/ Dhaani Dhaani, Baatein Teri, Udte Phirte Panchhiyon Ke Rukh Bhi Mode/ Adhoori Thi Zara Si, Main Poori Ho Rahi Hoon, Teri Saadgi Mein Hoke Choor...  ///////
  Ban ke titli dil udaa udaa udaa hai kaheen door / Chal ke khushboo se judaa judaa judaa hai kahin door /////// Wo… Yei.. Yei.. Yei.. Yeah.. O... ///////
  Raatein Gin Ke, Neendein Bun Ke, Cheez Kya Hai, Khwaabdaari Humne Jaani / Tere Sur Ka, Saaz Banke, Hote Kya Hain Raagdaari Humne Jaani / Jo Dil Ko Bha Rahi Hai Woh Teri Shayari Hai, Ya Koi Shayarana Hai Fitoor... ///////
  Ban ke titli dil udaa udaa udaa hai kaheen door / Chal ke khushboo se judaa judaa judaa hai kahin door /////// Haadse ye kaise, ansune se jaise / Choome andheron ko, koi noor.. ///////
  Ban ke titlee dil udaa udaa uda hai kahin door.. /////// Sirf keh jaaun yaa aasmaan pe likh doon / Teree taareefon mein chashme baddoor /////// Kondhal Vannanai Kovalanaai ///////
  Vennai Unda Va Yennin Ullam Kavarthanae / Kondhal Vannanai Kovalanaai / Vennai Unda Va Yennin Ullam Kavarthanae / Anda Kula Ne Arandha Nin Amudinai (x2) / Kanda Kangal Mai Thonrinai Kaanathey ///////`,

  '3.mp3': `Abhi kuch dino se lag raha hai / Badle badle se hum hai / Hum baithe baithe din mein sapne / Dekte neendein kam hai, /////// Abhi kuch dino se lag raha hai / Badle badle se hum hai / Hum baithe baithe din mein sapne / Dekte neendein kam hai, /////// Abhi kuch dino se suna hai dil ka / Rob hi kuch naya hai / Koi raaz kambakht hai chupaye / khuda hi jaane ki kya hai / Hai dil pe shaq mera ///////  Ise pyaar ho gaya, ///////  Abhi kuch dino se main sochta hoon / ki dil ki thodi si sun loon / Yaha rehne aayegi / Dil saja loon mein khwab thode se boon loon / Hai dil pe shaq mera / Ise pyaar ho gaya, ///%/// Tu bekhabar , Ya sab khabar / Ek din zara mere masoom dil pe gaur kar / Pardon mein main rakh loon tujhe / Ki dil tera aa na jaaye kahin yeh gair par ///////  Hum bhole hai , Sharmile hai / Hum hai zara siddhe masoom itni khair kar / Jis din kabhi / Zidd pe ade / Hum ayenge aag ka tera dariya tair kar ///////  Abhi kuch dino se lage mera dil / Duth ho jaise nashe mein / kyun lad khadaye yeh beheke gaye / hai tere har raaste pe / Hai dil pe shaq mera ///////  Ise pyaar ho gaya, ///\^/// Manke shehar chal raat bhar / Tu aur main toh musafir bhatakte hum phire / Chal raaste jahan le chale / Sapnon ke phir teri aahon mein thak ke hum gire /////// Koi pyaar ki , Tarkeeb ho / Nuskhe koi jo sikhaye toh hum bhi seekh le / Yeh pyaar hai rehta kaha / Koi humse kahe us se jaa k pooch le ///////  Mein sambhaloon pau Pisal na jau / Nayee nayee dosti hai / Zara dekh bhal sambhal ke chalna / Keh rahi zindagi hai / Hai dil pe shaq mera ///////  Ise pyaar ho gaya, /////// Abhi kuch dino se suna hai dil ka / Rob hi kuch naya hai / Koi raaz kambakht hai chupaye / Khuda hi jaane ki kya hai / Hai dil pe shaq mera ///////  Ise pyaar ho gaya. . .`,

  '4.mp3': `Chaahe kuch na kehna / Bhale chup tu rehna / Mujhe hai pata, tere pyar ka / Khamosh chehra, ankhon pe pehra / Khud hai gawaah, tere pyar ka /////// Teri jhuki nazar, teri har ada / Mujhe keh rahi hai ye dastaan / Koi shaqs hai jo ki in dinon / Tere zehan-o-dil pe hai chha gaya / Teri jhuki nazar, teri har ada / Mujhe keh rahi hai ye dastaan /////// Teri zulf jab bhi bikhar jaati hai / Aye haseen tu haseen aur ho jaati hai / Jo kitaabo me padhte rahe aaj tak / Woh pari humko tujh mein nazar aati hai /////// Teri hi baahon mein, panaahon mein / Rehna mujhe hardum sada / Teri hi yaadon mein, nigaahon mein / Rehna mujhe har dum sada / Teri hi baahon me, panaahon me / Rehna mujhe hardum sada / Hardum sada /////// Chaahe kuch na kehna / Bhale chup tu rehna / Mujhe hai pata tere pyar ka / Khamosh chehra, aankhon pe pehra / Khud hai gawaah, tere pyar ka /////// Teri jhuki nazar, teri har ada / Mujhe keh rahi hai ye dastaan / Koi shaqs hai jo ki in dinon / Tere zehan-o-dil pe hai chha gaya / Teri jhuki nazar, teri har ada / Mujhe keh rahi hai ye dastaan`,
  
  '5.mp3': `Surili Aanhkiyon Wale / Suna Hai Teri Aankhiyon Se / Behti Hai Neendein Aur / Neendon Mein Sapne / Kabhi To Kinare Pe / Utar Mere Sapno Se / Aaja Zameen Pe Aur Mil Ja Kahin Pe / Mil Ja Kahin / O o o /////// Mil Ja Kahin Samay Se Pare / Samay Se Pare / Mil Ka Kahin ////// / Tu Bhi Aankhiyon Se Kabhi / Meri Aankhiyon Ki Sun / Surili Aanhkiyon Wale / Suna Hai Teri Aankhiyon Se /////// Jane Tu Kahan Hai / Udti Hawa Pe Tere / Pairo Ki Nishan Dekhe ////// / Jane Tu Kahan Hai / Udti Hawa Pe Tere / Pairo Ki Nishan Dekhe /////// Dhondha Hai Zameen Pe / Jana Hai Falak Pe / Sare Aasmaan Dekhe / Mil Ja Kahin Samay Se Pare / Samay Se Pare / Mil Ka Kahin / Tu Bhi Aankhiyon Se Kabhi / Meri Aankhiyon Ki Sun /////// Everytime I Looking To Ur Eyes / I See My Paradise / These Stars Are Shining / Were Up In The Sky / Painting World Of Desire /////// You Are The One I Wating For /// Everytime I Looking To Ur Eyes / I See My Paradise / These Stars Are Shining / Were Up In The Sky / Painting World Of Desire /////// Ooth Mein Chupke / Dekh Rahe The / Chand Ke Peeche Peeche The ////// / Ooth Mein Chupke / Dekh Rahe The / Chand Ke Peeche Peeche The //////// Sara Jahan Dekha / Dekha Na Aankhon Mein / Palkon Ke Neeche The / Aa Chal Kahin / Samay Se Pare / Samay Se Pare / Chal De Kahin / Tu Bhi Aankhiyon Se Kabhi / Meri Aankhiyon Ki Sun //////// Surili Aanhkiyon Wale / Suna Hai Teri Aankhiyon Se / Surili Aanhkiyon Wale / Suna De Zara Aankhiyon Se / Surili Aanhkiyon Wale / Suna De Zara Aankhiyon Se`,

  '6.mp3': `Paya maine paya tumhein / Rab ne milaya tumhein / Honthon pe sajaya tumhein / Naghme sa gaya tumhein / Paya maine paya tumhein / Sab se chhupaya tumhein / Sapna banaya tumhein / Neendon mein bulaya tumhein  /////// Tum jo aaye zindagi mein baat ban gayi / Ishq mazhab, ishq meri zaat ban gayi /////// Paya maine paya tumhein / Rab ne milaya tumhein / Honthon pe sajaya tumhein / Naghme sa gaya tumhein / Paya maine paya tumhein / Sab se chhupaya tumhein / Sapna banaya tumhein / Neendon mein bulaya tumhein / Ho.. tum jo aaye zindagi mein baat ban gayi / Sapne teri chahaton ke / Sapne teri chahaton ke dekhti hoon kai / Din hai sona, aur chaandi raat ban gayi / Ho tum jo aaye zindagi mein baat ban gayi.. /////// Paya maine paya tumhein / Rab ne milaya tumhein / Honthon pe sajaya tumhein / Naghme sa gaya tumhein / Paya maine paya tumhein / Sab se chhupaya tumhein / Sapna banaya tumhein / Neendon mein bulaya tumhein / > / Chahaton ka maza faasalon mein nahi / Aa chhupa loon tumhein hauslon mein kahin / Sab se upar likha hai tere naam ko / Khwahishon se jude silsilon mein kahin / Khwahishein milne ki tumse / Khwahishein milne ki tumse roz hoti hain nayi / Mere dil ki jeet meri maat ban gayi / Ho tum jo aaye zindagi mein baat ban gayi..///\$/// Paya maine paya tumhein / Rab ne milaya tumhein / Honthon pe sajaya tumhein / Naghme sa gaya tumhein / Paya maine paya tumhein / Sab se chhupaya tumhein / Sapna banaya tumhein / 
            Neendon mein bulaya tumhein /////// Zindagi bewfa hai yeh mana magar / Chhodkar raah mein jaaoge tum agar / Chheen launga main, aasman se tumhein / Suna hoga na yeh, do dilon ka nagar / Raunkein hain dil ke dar pe / Raunkein hain dil ke dar pe / Dhadkanein hain surmayi / Meri kismat bhi tumhare sath ban gayi / Ho tum jo aaye zindagi mein baat ban gayi / Ishq mazhab, ishq meri zaat ban gayi / Sapne teri chahaton ke / Sapne teri chahaton ke dekhti hoon kai / Din hai sona, aur chaandi raat ban gayi / Ho tum jo aaye zindagi mein baat ban gayi.. /////// Paya maine paya tumhein / Rab ne milaya tumhein / Honthon pe sajaya tumhein / Naghme sa gaya tumhein / Paya maine paya tumhein / Sab se chhupaya tumhein / Sapna banaya tumhein / Neendon mein bulaya tumhein /////// Paya maine paya tumhein / Rab ne milaya tumhein / Honthon pe sajaya tumhein / Naghme sa gaya tumhein / Paya maine paya tumhein / Sab se chhupaya tumhein / Sapna banaya tumhein / Neendon mein bulaya tumhein`,

  '7.mp3': `O Nadaan Parindey ghar aaja // < // O Nadaan Parindey ghar aaja / O Nadaan Parindey ghar aaja / Ghar aaja… Ghar aaja… Ghar aaja aa aa.. /////// Kyun desh-bidesh phire maara / Kyun haal-behaal thaka haara / Kyun desh-bidesh phire maara / Tu raat-biraat ka banjara / O Nadan Parinde ghar aaja / Ghar aaja… Ghar aaja… Ghar aaja aa aa.. /////// Naadan Parinde ghar aaja… / Naadan Parinde ghar aaja… / Naadan Parinde ghar aaja… / Naadan Parinde ghar aaja… / Sau dard badan pe phele hain / Har karam ke kapde mele hain ///!/// Kaate chahe jitna paro se hawao’n ko / Khud se naa bach paayega tu / Tod aasmaano ko / Phook de jahaano ko / Khud ko chhupa naa payega tu / Koi bhi le rasta, tu hai tu mein basta / Apne hi ghar aayega tu /////// O Nadaan … / O Nadaan parindey ghar aaja / Ghar aaja… Ghar aaja… Ghar aaja aa aa.. / Nadaan Parindey ghar aaja / Nadaan Parindey ghar aaja / Nadaan Parindey ghar aaja / Naadan Parinde ghar aaja…. //!// Kaaga re kaaga re mori itni  araj tose / Chun chun khaaiyo maans / Kaaga re kaaga re mori itni araj tose / Chun chun khaaiyo maans /////// Arajiya re khaaiyo na tu  naina more / Khaaiyon na tu naina mohe / Piya ke milan ki aas / Khaaiyon na tu naina more / Khaaiyon na tu naina mohe / Piya ke milan ki aas ///////  O Nadaan … / O Nadaan parindey ghar aaja / Ghar aaja… Ghar aaja… Ghar aaja aa aa.. /////// Naadan Parinde ghar aaja…(8)`,

  '8.mp3': `Mann yeh saahib ji jaane hai sab ji  / Phir bhi banaye bahaane  / Naina nawaabi ji dekhe hain sab ji  / Phir bhi na samjhe ishaare  / Mann yeh saahib ji haan karta bahaane  / Naina nawaabi ji na samjhe ishaare   /////// Dheere dheere, nainon ko dheere dheere jiya ko  / Dheere dheere, bhaayo re Saibo  / Dheere dheere, begaana dheere dheere apna na  / Dheere dheere, laage re Saibo  ///@/// Surkhhiyaan hain hawaaon mein  / Do dilon ke milne ki  / Ho arziyaan hain nazaaron mein  / Lamha yeh tham jaane ki  / O kaisi huzoori ji yeh lab dikhlaaye  / Chuppi laga ke bhi ghazab hai yeh dhaaye   /////// Dheere dheere, nainon ko dheere dheere jiya ko  / Dheere dheere, bhaayo re Saibo  / Dheere dheere, begaana dheere dheere apna na  / Dheere dheere, laage re Saibo  / Saibo `,

  '9.mp3': `Ya Nizamuddin Auliya, Ya Nizamuddin Salqa / Kadam Badhaa Le, Hadon Ko Mitaa Le, / Aaja Khaalipan Mein Pee Ka Ghar Tera, / Tere Bin Khaali Aaja, Khalipan Mein / Tere Bin Khaali Aaja, Khalipan Mein  /////// Oooooo... Oooooo...  Oooooo... Oooooo... / Oooooo...  Rangreza /////// Rangreza  Rangrezaa... ////// Ho... Rang-Rezaaaa... ///\$/// Kun Faya Kun  Kun Faya Kun / Faya Kun, Faya Kun, Faya Kun, Faya Kun / Kun Faya Kun  Kun Faya Kun / Faya Kun,  Faya Kun, Faya Kun, Faya Kun /////// Jab Kahin Pe Kuch Nahi Bhi Nahi Tha / Wahi Tha Wahi Tha Wahi Tha Wahi Tha / Jab Kahin Pe Kuch Nahi Bhi Nahi Tha / Wahi Tha Wahi Tha Wahi Tha Wahi Tha /////// Woh Jo Mujh Mein Samaya / Woh Jo Tujh Mein Samaya / Maula Wahi Wahi Maaya / Woh Jo Mujh Mein Samay / Woh Jo Tujh Mein Samaya / Maula Wahi Wahi Maaya /////// Kun Faya Kun / Kun Faya Kun / Sadaqallahul-Alliyul-Azeem /// % /// Rangreza Rang Mera Tan Mera Man, / Le Le Rangaayi Chaahe Tan Chaahe Man / Rangreza Rang Mera Tan Mera Man, / Le Le Rangaayi Chaahe Tan Chaahe Man /////// Sajra Savera Mere Tan Barse / Kajra Andhera Teri Jalti Lau ///>///  Sajra Savera Mere Tan Barse / Kajra Andhera Teri Jalti Lau / Katra Mila Jo Tere Dar Par Se / O Maula... Maula... Aaa.../////// Kun Faya Kun / Kun Faya Kun / Kun Faya Kun / Kun Faya Kun / Kun Faya Kun / Kun Faya Kun / Faya Kun, /////// Faya Kun, Faya Kun, Faya Kun / Kun Faya Kun / Kun Faya Kun / Faya Kun, / Faya Kun, Faya Kun, Faya Kun / 
            Jab Kahin Pe Kuch Nahi Bhi Nahi Tha / Wahi Tha Wahi Tha Wahi Tha Wahi Tha / Jab Kahin Pe Kuch Nahi Bhi Nahi Tha / Wahi Tha Wahi Tha Wahi Tha Wahi Tha /////// Kun Faya Kun / Kun Faya Kun / Sadaqallahul-Alliyul-Azeem' / Sadaqa Rasulu-Hun Nabi-Yun-Kareem / Sallallaahu Alayhi Wasallam, Sallallaahu Alayhi Wasallam /////// O Mujhpe Karam Sarkar Tera / Araz Tujhe, Karde Mujhe, Mujhse Hi Riha / Ab Mujhko Bhi Ho, Deedaar Mera / Karde Mujhe, Mujhse Hi Riha / Mujhse Hi Rihaaaaaaaa / Mann Ke Mere Ye Bharam / Kachche Mere Ye Karam / Leke Chale Hai Kahaan / Main Toh Jaanoon Hi Na /////// Tu Hai Mujh Mein Samaya, / Kahaan Leke Mujhe Aaya / Main Hoon Tujh Mein Samaya, / Tere Peeche Chala Aaya / Tera Hi Main Ek Saaya / Tune Mujhko Banaya / Main Toh Jag Ko Na Bhaaya / Tune Gale Se Lagaya / Ab Tu Hi Hai Khudaya / Sach Tu Hi Hai Khudaya /////// Kun Faya Kun Kun Faya Kun / Faya Kun, Faya Kun, Faya Kun, / Faya Kun Kun Faya Kun / Kun Faya Kun /////// Faya Kun, / Faya Kun, Faya Kun, Faya Kun / Jab Kahin Pe Kuch Nahi Bhi Nahi Tha / Wahi Tha Wahi Tha Wahi Tha Wahi Tha / Jab Kahin Pe Kuch Nahi Bhi Nahi Tha / Wahi Tha Wahi Tha Wahi Tha Wahi Tha /////// Kun Faya Kun Kun Faya Kun / Sadaqallahul-Alliyul-Azeem' / Sadaqa Rasulu-Hun Nabi-Yun-Kareem / Sallallaahu Alayhi Wasallam, Sallallaahu Alayhi Wasallam `,

'10.mp3': ``,

'11.mp3': ``,

  // Add more songs as needed
};
// 🔧 Step 1: Your songLyrics data should be defined somewhere
function getLyrics(filename) {
  const rawLyrics = songLyrics[filename] || "Lyrics not available.";
  return rawLyrics
    .split('/') // Split by lines
    .map(line => {
      return line
        .replace(/</g, '<img src="Instru/drum.png" alt="drum" class="emoji-img">')
        .replace(/>/g, '<img src="Instru/piano.png" alt="piano" class="emoji-img">')
        .replace(/!/g, '<img src="Instru/electric.png" alt="electric" class="emoji-img">')
        .replace(/@/g, '<img src="Instru/Violin.png" alt="Violin" class="emoji-img">')
        .replace(/#/g, '<img src="Instru/Oud.png" alt="Oud" class="emoji-img">')
        .replace(/\$/g, '<img src="Instru/Tabla.png" alt="Tabla" class="emoji-img">')
        .replace(/%/g, '<img src="Instru/AcousticGuitar.png" alt="violin" class="emoji-img">')
        .replace(/\^/g, '<img src="Instru/Harmonica.png" alt="Harmonica" class="emoji-img">')
        .replace(/&/g, '<img src="Instru/tambourine.png" alt="tambourine" class="emoji-img">')
        .replace(/\*/g, '<img src="Instru/trumpet.png" alt="trumpet" class="emoji-img">')
        .replace(/\?/g, '<img src="Instru/bongo.png" alt="bongo" class="emoji-img">');
    });
}


// ✅ Step 2: Wait for DOM content before accessing elements
document.addEventListener('DOMContentLoaded', () => {
  const audio = document.getElementById('audio'); // Ensure you have <audio id="audio">
  const lyricsText = document.getElementById('lyrics-text');

  audio.addEventListener('play', () => {
    const filename = audio.currentSrc.split('/').pop();
    const lyricsLines = getLyrics(filename);

    // Clear previous lyrics only
    lyricsText.innerHTML = '';

    // Add each line, allowing inline image
    lyricsLines.forEach(line => {
      const lineElement = document.createElement('div');
      lineElement.innerHTML = line;
      lyricsText.appendChild(lineElement);
    });
  });
});
